#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Update Nginx default configuration to listen on port 80
echo "server { listen 80; }" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Create a symbolic link to enable the default site
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
