#!/usr/bin/env bash
# This Script handles SIGTERM signal

trap 'echo "I am invincible!!!"; exit' SIGTERM

# Display "To infinity and beyond" indefinitely with a 2-second delay between iterations
while true; do
    echo "To infinity and beyond"
    sleep 2
done

