#!/usr/bin/env bash
#This Script prints "bad luck" on 4th iteration "good luck" on *th iteration and "Best School" Elsewhere


counter=1

while [ $counter -le 10 ]; do
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi

	((counter++))

done
