#!/usr/bin/env bash
#This Script prints 1 to 20 with some conditions in between

counter=1

while [ $counter -le 20 ]; do
	case $counter in
		4)
			echo $counter
			echo "bad luck from China"
			;;
		9)
			echo $counter
                        echo "bad luck from Japan"
                        ;;
		17)
			echo $counter
                        echo "bad luck from Italy"
                        ;;
		*)
			echo $counter
			;;
	esac


	((counter++))
done
