#!/usr/bin/env bash
#This Script prints the 12 hours of a clock and minutes


hour=0
minutes=1

while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	while [ $minutes -lt 60 ]; do
		echo $minutes
		
		((minutes++))
	done

	minutes=1

	((hour++))
done
