# Use the official Apache image as the base image
FROM httpd:2.4

# Copy a custom index.html file to the Apache document root
COPY index.html /usr/local/apache2/htdocs/

# Expose port 80 to the outside world
EXPOSE 80

